name: project3
channels:
  - conda-forge
dependencies:
  - python=3.10
  - numpy
  - pandas
  - matplotlib
  - seaborn
  - scikit-learn
  - pillow
  - opencv
  - jupyter
  - ipykernel
  - pip
  - tensorflow
  - pip:
      - piexif==1.1.2